spring:
  application:
    name: user-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: micro
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: 418032
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true