spring:
  application:
    name: product-service
  profiles:
    active: micro
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: 418032
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true