spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_project
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect