spring:
  application:
    name: inventory-service
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: micro
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password: 418032
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect