version: '2.1'
services:
  postgresql_db:
    image: postgres:15
    volumes:
      - postgresql_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgresql_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432" 

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql_db/postgresql_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - "9090:8080"
    command:
      - start-dev
volumes:
  postgresql_db: